### ISSUE TITLE
PCA

### ISSUE THREAD

**Issue by mente371** [KevinCoble/AIToolbox#15]
i) Your library is great.
ii) In the function "getReducedBasisVectorSet(_ data: MLDataSet)", 
at the end when you create the basisVectors matrice, should it not be
basisVectors[(vector * **initialDimension**) + column] = vTranspose[vector + (column * initialDimension)]
instead of 
basisVectors[(vector * **reducedDimension**) + column] = vTranspose[vector + (column * initialDimension)]
?

**Comment by KevinCoble** [comment]
i)  Thanks!  It will be great to see what you do with it.

ii)  I think you may be right.  I am adding additional code to the XCTest file for PCA to verify the transformDataSet function that uses the basis vectors.  I hope to get an update out in a couple of days.

**Comment by KevinCoble** [comment]
Updated a change today.
The new testing hopefully shows it working correctly for multiple basis vectors.

Thanks for finding the issue.
