### ISSUE TITLE
Contribution list / checklist

### ISSUE THREAD

**Issue by codeOfRobin** [KevinCoble/AIToolbox#2]
Hey!
I came across this project and was wondering if you guys could build a checklist of TODOs etc for potential contributors.

Something like
- [ ] Benchmarks
- [ ] CNNs
- [ ] POMDPs
  ..etc?

**Comment by KevinCoble** [comment]
I have added a contributions page.  I need to learn how to make it flow better in the markdown language, but it is a start.  Suggestions on the best way to acknowledge that someone is actively working on a particular addition would be welcome.  I will leave this issue open so comments can be added until I get the contributions page formatted better.

**Comment by KevinCoble** [comment]
I formatted the contribution page better.  I will close this issue now, but comments on how to improve the process will always be welcome.  I put my email address on the contribution page if needed.  Thanks for the suggestion.
