### ISSUE TITLE
Nonlinear Regression and Logistic Regression Examples

### ISSUE THREAD

**Issue by TheBitingGoat** [KevinCoble/AIToolbox#22]
Do you have any documentation or examples of how to use nonlinear regression and logistic regression?

**Comment by KevinCoble** [comment]
The source files for the test modules show how to use the classes.  Look in the AIToolboxTests directory for the LogisticRegressionTests.swift and NonLinearRegressionTests.swift files.

**Comment by TheBitingGoat** [comment]
Much appreciated...I was looking for documentation in the manual. Thanks for the help, the library is great.
