### ISSUE TITLE
Implementation of correlation

### ISSUE THREAD

**Issue by AJamesPhillips** [KevinCoble/AIToolbox#4]
I implemented a simple correlation function borrowing heavily from Numpy's implementation ([here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/multiarraymodule.c#L1087-L1201) and [here](https://github.com/numpy/numpy/blob/master/numpy/core/src/multiarray/multiarraymodule.c#L1249-L1318)).  If this is something you'd like to see in the library would you like me to submit a pull request?  I'm not yet sure where the best place for this is within the library.

https://gist.github.com/AJamesPhillips/7ea56a3a217be300a5705a8109c73a5b

Thanks

**Comment by KevinCoble** [comment]
The correlate function (and most of numpy in general) is more of a vector math operator than an Artificial Intelligence/Machine Learning algorithm.  Is there a known use case for it in AI or ML?  If so, I would be happy to accept a pull request.  If not, check out the 'Math' section of the 'awesome-ios' github project.  There are several frameworks there that it would fit in.
I would recommend a couple of things though.  First, the dot-product function should probably be replaced with the vDSP version of the function (or at least use it internally) which uses the vector processor and is many times faster.  Second, the new Swift API guidelines frown upon strings as enumerations - I would change the mode to an actual enumeration.

**Comment by AJamesPhillips** [comment]
Excellent feedback thanks.

We're employing it in some of the many features an AI algo uses and you're correct that a maths / numerical library would be better suited.  AIToolbox is like sklearn, which uses numpy but doesn't have it's functions.  Thanks, got a bit too exited at the prospect of contributing to the library.

I saw the dot product function calls in the library last night but lacked the brain power to reuse.  Will check out vDSP and enums.  Thanks again Kevin!

**Comment by KevinCoble** [comment]
For an example of the vDSP dot-product, look at the code for feed-forward method in the simple neural net.  The code is:

```
103         var z = 0.0 
104         vDSP_dotprD(W, 1, x, 1, &z, vDSP_Length(W.count)) 
```

This code dot-products the W weight vector with the x input vector, resulting in z
