### ISSUE TITLE
Can not import into Swift Project

### ISSUE THREAD

**Issue by heuism** [KevinCoble/AIToolbox#5]
I have done exactly what the manual showed. But still. When i tried to import AIToolbox into Xcode project (my iphone application project) i couldn't do it?

That would be nice to get your help. Thanks.
![screen shot 2017-01-24 at 12 16 15 pm](https://cloud.githubusercontent.com/assets/8481265/22229948/fa563e18-e22e-11e6-8ec3-83a31fd77f68.jpg)

**Comment by KevinCoble** [comment]
Have you copied the built framework into the /Library/Frameworks directory?  Since I use the framework in multiple projects I have found it easier to put it in that global location, and haven't researched how to set framework search paths in a referencing project.

**Comment by heuism** [comment]
Thanks for your quick reply!

Yeah i did as you showed in the manual! As i read the error i look into the file AIToolbox.h and it got the #import <Cocoa> something! And i find out that iPhone doesn't support using that, only Mac does! Does that mean that this framework can only support Mac App! Please say i am wrong :)!

Or if this one can support iOS, please show me how to do it :)!

Thanks for your help so much!

**Comment by KevinCoble** [comment]
When you build it, you must select the scheme (use menu Product->Scheme) AIToolboxIOS to get the iOS version.

As I do most work on macOS, I have just moved the files I needed from the AIToolbox folder to my iOS projects and used AIToolbox as a full framework for just macOS.  I will try to make an iOS project with an embedded framework and update the manual with instructions if I am successful (Build settings are not something I am very comfortable with).

**Comment by KevinCoble** [comment]
OK, I made a project and embedded the framework (Thanks to Ray Wenderlich.com and Michael Katz - https://www.raywenderlich.com/126365/ios-frameworks-tutorial).  Here is what I did:

Have both the AIToolbox and your application projects open in Xcode.  Make sure the AIToolbox scheme for iOS has been successfully built.

Right-click on the root application node in the project navigator. Click Add Files to “<application>”. In the file chooser, navigate to and select AIToolbox.xcodeproj. This will add AIToolbox.xcodeproj as a sub-project.

Expand the AIToolbox project to see the Products folder, and then look for for AIToolbox.framework beneath it. This file is the output of the framework project that packages up the binary code, headers, resources and metadata.  There are three outputs.  The iOS framework is the middle one.

In your application project, select the top level application node to open the project editor. Click the application target, and then go to the General tab.  Scroll down to the Embedded Binaries section.

Drag AIToolbox.framework (the middle one!) from the Products folder of AIToolbox.xcodeproj onto this section.  It will ask about grouping and references.  Select “copy items if needed” and click “Finish”  Rebuild your project and it should hopefully link


I will add this to the manual shortly.  Hope this does the trick.

**Comment by KevinCoble** [comment]
I have not heard if the new iOS instructions helped you or not.  I have updated the manual and will close the issue soon if I haven't heard that there are additional issues.

**Comment by heuism** [comment]
Sorry for delaying! I will try this method of you soon on Monday! Cuz i have been busy with Lunar New Year events recently and forget to check this! Thanks for your hard work and patient, i really appreciated your ethic

**Comment by heuism** [comment]
@KevinCoble, thanks for your help, i successfully imported it into the project. Outstanding support i must say. I would like to say thank you again. I would ask another question about the algorithms that this support if i run into any. I will close this issue. 👍
