### ISSUE TITLE
Is there a deconvoltuion network (Transpose Network) support plan?

### ISSUE THREAD

**Issue by clyne83** [KevinCoble/AIToolbox#9]
Hello

Is there a deconvoltuion network (Transpose Network) support plan?

thanks.

**Comment by KevinCoble** [comment]
There currently is not.  The framework is a collection of code I have worked on to play with pieces of AI and learn about them.  I am currently playing with natural language parsing.  Maybe someday I'll get back to convolutional networks.

I would always welcome someone else adding to the framework, and that is an area where there is currently a deficiency.
